spin_manifest_version = "1"
authors = ["Winnie <luwinnie12@gmail.com>"]
description = ""
name = "test"
trigger = { type = "http", base = "/" }
version = "0.5.0"

[variables]
token = { required = true }
username = { required = true }
password = { required = true }

[[component]]
id = "backend"
source = "backend/app.wasm"
allowed_http_hosts = [
    "https://fermyon.metabaseapp.com",
    "https://api.hubapi.com",
]
sqlite_databases = ["default"]
[component.trigger]
route = "/"
[component.build]
command = "spin py2wasm app -o app.wasm"
workdir = "backend"
watch = ["app.py", "Pipfile"]
[component.config]
token = "{{token}}"
username = "{{username}}"
password = "{{password}}"
metabase_host = "https://fermyon.metabaseapp.com"
hubspot_host = "https://api.hubapi.com"
